spring:
  application:
    name: message-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.taptalk.message.model

server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://211.187.162.65:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    com.taptalk.message: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.cloud: DEBUG
    com.netflix.eureka: DEBUG
